import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });
// import Game from "./game";
import dynamic from "next/dynamic";

const Game = dynamic(() => import("./game"), { ssr: false });
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next Game</title>
        <meta name="description" content="Generated by create next Game" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Game />
    </>
  );
}
